mgres = readlines('/media/ironman/IRON-MAN-Imaging/list/mgres_dbs_comb'); 

for j = 1:numel(mgres)-1
    disp(strcat('Reconstructing',{' '},mgres(j)))
    mgre_path = char(mgres(j));
    subdir = mgre_path(3:end);
    cd(strcat('/media/ironman/IRON-MAN-Imaging/',subdir))
    cd ..
    mgre_dir = mgre_path(end-20:end);
    disp(mgre_dir)
    mkdir mat
    % Import complex field data
    if ~exist('./mat/QSM_dbs.mat','file')
        try
            [iField,voxel_size,matrix_size,CF,delta_TE,TE,B0_dir,files]=Read_DICOM(mgre_dir);
            cd('mat')
            save iField.mat iField voxel_size matrix_size CF delta_TE TE B0_dir files
            % Generate the magnitude image 
            iMag = squeeze(sqrt(sum(abs(iField).^2,4)));

            % Compute brain mask
            Mask = BET(iMag,matrix_size,voxel_size);

            % Estimate noise and normalize field
            if (~exist('noise_level','var'))
                noise_level = calfieldnoise(iField, Mask);
            end
            iField = iField/noise_level;

            % Estimate the frequency offset in each of the voxel using complex fitting 
            [iFreq_raw,N_std] = Fit_ppm_complex_bipolar(iField);

            % Fit R2* map
            R2s = arlo(TE,abs(iField));

            % CSF zero-reference
            Mask_CSF = extract_whole_CSF(R2s,Mask,voxel_size);

            % Spatial phase unwrapping (region-growing)
            % Bipolar fitting fits even and odd echoes separately
            % Results in effective 2dTE
            % Wraps occur at pi rather than 2 pi
            % Fix this by multiplying by 2
            iFreq = (1/2)*unwrapPhase(iMag, 2*iFreq_raw, matrix_size);

            % Background field removal
            [RDF,shim] = PDF(iFreq,N_std,Mask,matrix_size,voxel_size,B0_dir,0,100);

           
            % Save local field generated by PDF
            save RDF_dbs.mat RDF iMag N_std Mask matrix_size voxel_size delta_TE CF B0_dir Mask_CSF R2s iFreq iFreq_raw;

            % Reconstruct QSM
            QSM = MEDI_L1('filename', 'RDF_dbs.mat', 'lambda', 1000, 'merit', 'msmv', 5);
            save QSM_dbs QSM
        catch
            disp('Reconstruction failed')
        end
    else
        disp(strcat('Found QSM for',{' '},mgres(j)))
        QSM = load('./mat/QSM_dbs.mat').QSM;
        niftiwrite(QSM,'QSM_msmv_dbs','Compressed',true)
    end
    cd('/media/ironman/IRON-MAN-Imaging/')
end